filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields:
      log_type: access
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log
    fields:
      log_type: error
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://golang-collector:8080"]
  path: "/collect"
  protocol: "http"  # Chỉ định rõ là dùng http
  bulk_size: 50
  compression_level: 0 # Tắt nén để giảm tải cho golang-collector
  ssl.verification_mode: none # Tắt kiểm tra SSL vì bạn dùng http

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
